#!/bin/bash

SOCKETNAME="/run/haproxy/admin.sock"
BACKENDNAME="ibgrtv"

case $1 in
   config)
        cat <<EOM
graph_title HAproxy backend stats
graph_args --base 1000 -l 0
graph_scale no
graph_category HAproxy
graph_vlabel Sessions
graph_info HAproxy backend statistics
EOM

    STATS=`echo "show stat" | socat stdio $SOCKETNAME | grep -v BACKEND | grep ${BACKENDNAME}`
    TOTALLIM=0
    while read line ; do
        LIMIT=`echo $line | awk -F ',' '{print $7}'`
        TOTALLIM=$(($TOTALLIM+$LIMIT))
        WARN=$((LIMIT*75/100))
        CRIT=$((LIMIT*90/100))
        NODENAME=`echo $line | awk -F ',' '{print $2}'`

        echo "backend_${BACKENDNAME}_${NODENAME}_sessions.label ${NODENAME} sessions"
        echo "backend_${BACKENDNAME}_${NODENAME}_sessions.warning ${WARN}"
        echo "backend_${BACKENDNAME}_${NODENAME}_sessions.critical ${CRIT}"
    done <<<"$STATS"
    TOTALWARN=$((TOTALLIM*75/100))
    TOTALCRIT=$((TOTALLIM*90/100))
    echo "backend_${BACKENDNAME}_total_sessions.label total sessions"
    echo "backend_${BACKENDNAME}_total_sessions.warning ${TOTALWARN}"
    echo "backend_${BACKENDNAME}_total_sessions.critical ${TOTALCRIT}"
esac

STATS=`echo "show stat" | socat stdio $SOCKETNAME | grep -v BACKEND | grep ${BACKENDNAME}`
TOTALSESSIONS=0
while read line ; do
    NODENAME=`echo $line | awk -F ',' '{print $2}'`
    SESSIONS=`echo $line | awk -F ',' '{print $5}'`
    TOTALSESSIONS=$(($TOTALSESSIONS+$SESSIONS))
    echo -n "backend_${BACKENDNAME}_${NODENAME}_sessions.value "
    echo "$SESSIONS"
done <<<"$STATS"
echo -n "backend_${BACKENDNAME}_total_sessions.value "
echo "$SESSIONS"

