#!/bin/bash

PLUGINNAME="asihpi_load"
HPICONTROL="/usr/local/bin/hpicontrol.py"
CARD=`${HPICONTROL} cget 1 info | head -n 1 | awk '{print $3}' | sed 's/,*$//g'`

case $1 in
   config)
        cat <<EOM
graph_title AudioScience $CARD DSP load
graph_args --base 1000 -l 0
graph_scale no
graph_category sound
graph_vlabel temperature in ºC
graph_info AudioScience ASIHPI driver card DSP load in %
${PLUGINNAME}.info ASIHPI DSP Load
${PLUGINNAME}.label load %
${PLUGINNAME}.warning 70
${PLUGINNAME}.critical 85
EOM
        exit 0;;
esac

if [ "$CARD" == "ASI5720" ] || [ "$CARD" == "5740" ] || [ "$CARD" == "5788" ]; then
    LEVEL=`${HPICONTROL} cget 10 | grep '\-\-int value' | awk '{print $3}'`
else
    LEVEL=`${HPICONTROL} info | grep DSP | awk '{print $5}'`
fi

echo -n "$PLUGINNAME.value "
echo "$LEVEL"



