#!/bin/bash

PLUGINNAME="asihpi_temp"
HPICONTROL="/usr/local/bin/hpicontrol.py"
CARD=`${HPICONTROL} cget 1 info | head -n 1 | awk '{print $3}' | sed 's/,*$//g'`

case $1 in
   config)
        cat <<EOM
graph_title AudioScience $CARD board temperature
graph_args --base 1000 -l 0
graph_scale no
graph_category sound
graph_vlabel temperature in ºC
graph_info AudioScience ASIHPI driver card Temperature Sensor Read in ºC
${PLUGINNAME}.info ASIHPI Temp
${PLUGINNAME}.label temperature ºC
${PLUGINNAME}.warning 65
${PLUGINNAME}.critical 75
EOM
        exit 0;;
esac

if [ "$CARD" == "ASI5720" ] || [ "$CARD" == "5740" ] || [ "$CARD" == "5788" ]; then
    LEVEL=`${HPICONTROL} cget 11 | grep '\-\-float value' | awk '{print $3}'`
else
    LEVEL=0
fi

echo -n "$PLUGINNAME.value "
echo "$LEVEL"

