#!/bin/sh

case $1 in
   config)
        cat <<'EOM'
graph_title Envy24-1 output level meter
graph_args --base 1000 -l 0
graph_scale no
graph_category sound
graph_vlabel peak meter
graph_info Sound peak meter level at the envy24 pcm output device
ossenvy24out.info Output level meter
ossenvy24out.label peak
EOM
        exit 0;;
esac

echo -n "ossenvy24out.value "
echo $(($(ossmix -d 1 -D |grep outvu |awk -F "=" '{print $NF}')))

